### ISSUE TITLE
Error after updating the library

### ISSUE THREAD

**Issue by luizfernandonb** [starflash-studios/QMediaVSIX#2]
**Describe the bug**
After I updated the extension, an error occurred and it no longer works, the translation is in English, but nothing else works

**To Reproduce**
1. Install the library if you don't have it or update it from an old version
2. Click any button

**Expected behavior**
The extension works normally

**Screenshots**
![image](https://user-images.githubusercontent.com/42288418/119209691-736b7580-ba7e-11eb-9019-c3c2f3d98284.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 90.0.818.62

**Additional context**
The [ActivityLog.xml](https://cdn.discordapp.com/attachments/478612177511645212/845463828983971840/ActivityLog.xml) (he is in portuguese)

**Comment by Neonalig** [comment]
I believed I've tracked the error down to CultureInfo.CurrentCulture being null in some occurrences. Since there's no proper null check available for the CultureInfo class, I've instead tried to 'find' a pure CultureInfo from the current culture's name, and if that fails (i.e. the current culture is null / empty), it'll just default to English.

I also caught a future error where the current culture isn't supported by an AppTranslation, and so it will default to English again in that case. In an upcoming version, I may add a manual language override for these circumstances.

![image](https://user-images.githubusercontent.com/16698604/119211217-6df44680-bae3-11eb-8893-ca8acc6b10e1.png)

**Comment by Neonalig** [comment]
The latest version was just released, and should fix this bug. It's also been uploaded to the Visual Studio Marketplace, and is just being verified now.
